environment:
  matrix_count: 1
  matrix:
    - PYTHON: "C:\\Python36-x64"

matrix:
  fast_finish: true

install:
  - echo Before
  - ps: >-
      $env:matrix_count = ($env:matrix_count - 1);
      Write-Output "matrix_count- $env:matrix_count";
      # this is a comment
      Write-Output "If you see this, then line endings are OK";

build: off

on_success:
  - ps: >-
      Write-Output "final matrix_count - $env:matrix_count";

